# Generated by Django 4.1.1 on 2022-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='designation',
            field=models.CharField(default='R', max_length=255),
        ),
    ]
