# Generated by Django 4.1.1 on 2022-09-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_members_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('startdate', models.DateTimeField(blank='True')),
                ('enddate', models.DateTimeField(blank='True')),
                ('category', models.CharField(choices=[('P', 'Programming'), ('W', 'Web Development'), ('D', 'DataAnalysis'), ('O', 'DevOps'), ('T', 'Testing'), ('X', 'Others')], max_length=255)),
                ('facultyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.members')),
            ],
        ),
    ]
