# Generated by Django 4.1.1 on 2022-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
        migrations.AddField(
            model_name='members',
            name='image_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
