# Generated by Django 4.1.1 on 2022-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_members_image_id_members_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='image',
            new_name='image_id',
        ),
    ]
