# Generated by Django 4.1.1 on 2022-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_members_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='image_id',
        ),
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='img'),
        ),
    ]
