# Generated by Django 4.1.1 on 2022-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_user_image_alter_uploadimage_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='image_id',
        ),
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(default=' ', upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
