# Generated by Django 4.1.1 on 2022-10-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_memberimage_remove_members_image_id_members_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('doj', models.DateTimeField(blank=True)),
                ('resume', models.URLField(default='')),
                ('skills', models.TextField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='MemberImage',
        ),
    ]
