# Generated by Django 4.1.1 on 2022-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_student_delete_memberimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
