# Generated by Django 4.1.1 on 2022-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_student_email_alter_student_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
